version: "3.7"

services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  # backend:
  #   image: backend
  #   container_name: backend
  #   restart: always
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./backend:/backend
  #   depends_on:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ce
    volumes:
      - "mysqldata:/var/lib/mysql"

  analysis:
    build:
      context: ./analysis
    command: python3 app.py
    environment:
      FLASK_DEBUG: 1
    ports:
      - 8888:8888

volumes:
  mysqldata: