spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheer
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

jwt:
  secret: cheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerupcheerup
